//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chwthewke.PasswordManager.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chwthewke.PasswordManager.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string CopyPasswordDefaultQualifier {
            get {
                return ResourceManager.GetString("CopyPasswordDefaultQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy {0} Password.
        /// </summary>
        internal static string CopyPasswordTemplate {
            get {
                return ResourceManager.GetString("CopyPasswordTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphanumeric.
        /// </summary>
        internal static string PasswordGenerator74728a1033d44245b7c95d72fc424c41 {
            get {
                return ResourceManager.GetString("PasswordGenerator74728a1033d44245b7c95d72fc424c41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        internal static string PasswordGeneratorccf1451c4b3045a499b0d54ec3c3a7ee {
            get {
                return ResourceManager.GetString("PasswordGeneratorccf1451c4b3045a499b0d54ec3c3a7ee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a 10-character password, using lower- and upper-case letters and digits..
        /// </summary>
        internal static string PasswordGeneratorDescription74728a1033d44245b7c95d72fc424c41 {
            get {
                return ResourceManager.GetString("PasswordGeneratorDescription74728a1033d44245b7c95d72fc424c41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates an 8-character password, using lower- and upper-case letters, digits, as well as special characters among: &amp; &quot; &apos; ( - _ ) = # { [ | \ @ ] } $ % * &lt; &gt; , ? ; . : / ! ^ `.
        /// </summary>
        internal static string PasswordGeneratorDescriptionccf1451c4b3045a499b0d54ec3c3a7ee {
            get {
                return ResourceManager.GetString("PasswordGeneratorDescriptionccf1451c4b3045a499b0d54ec3c3a7ee", resourceCulture);
            }
        }
    }
}
